CREATE TABLE [dbo].[Races]
(
	[race_type] varchar(10) NOT NULL,
	[race_id] VARCHAR(10) NOT NULL,
	[race_date] DATE NOT NULL, 
    [published_time] VARCHAR(4) NOT NULL, 
    [surface] VARCHAR(10) NOT NULL, 
    [type_of_race] VARCHAR(10) NOT NULL, 
    [course] VARCHAR(200) NOT NULL, 
    [track] VARCHAR(300) NOT NULL, 
    [distance] VARCHAR(30) NOT NULL, 
    [distance_in_yards] VARCHAR(50) NOT NULL, 
    [title] VARCHAR(30) NOT NULL, 
    [going] VARCHAR(50) NOT NULL, 
    [going_allowance] DECIMAL NOT NULL, 
    [race_time] DECIMAL NOT NULL, 
    [variation_from_med] DECIMAL NOT NULL, 
    [prize_1] DECIMAL NOT NULL, 
    [prize_2] DECIMAL NOT NULL, 
    [prize_3] DECIMAL NOT NULL, 
    [prize_4] DECIMAL NOT NULL, 
    [prize_5] DECIMAL NULL, 
    [prize_6] DECIMAL NULL, 
    [rider_type] VARCHAR(50) NULL, 
    [horse_type] VARCHAR(50) NOT NULL, 
    [age_range] VARCHAR(20) NOT NULL, 
    [conditions_type] VARCHAR(20) NULL, 
    [group_or_listed] VARCHAR(50) NULL, 
    [hcap_from] VARCHAR(10) NULL, 
    [hcap_to] VARCHAR(10) NULL, 
    [no_fences] VARCHAR(10) NULL, 
    [weights_raised_lbs] VARCHAR(10) NULL, 
    [class_of_race] VARCHAR(10) NULL,
)
